version: "3.7"
services:
  # mongodb:
  #   image: mongo:latest
  #   container_name: mongodb
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  #     MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
  #   ports:
  #     - 27018:27017
  #   volumes:
  #     - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  #     - ./mongodb/db:/data/db
  api:
    build: .
    container_name: portal-api
    ports:
      - "9213:9213"
    # volumes:
    #   - ./src:/usr/src/app/src
    restart: always
    env_file: .env
    # depends_on: 
    #   - mongodb

